blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Systemsaholic/phone-prompt-generator/blob/master/README.md
    about: Check the comprehensive documentation
  - name: 🚀 Deployment Guide
    url: https://github.com/Systemsaholic/phone-prompt-generator/blob/master/DEPLOYMENT.md
    about: Production deployment instructions
  - name: 🔒 Security Issue
    url: https://github.com/Systemsaholic/phone-prompt-generator/blob/master/SECURITY.md
    about: Report security vulnerabilities privately
  - name: 💬 Discussions
    url: https://github.com/Systemsaholic/phone-prompt-generator/discussions
    about: Ask questions and discuss ideas
