name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked the [planned features](https://github.com/Systemsaholic/phone-prompt-generator/blob/master/CHANGELOG.md#planned-features)
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - User interface improvement
        - API enhancement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when..., It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like the application to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also considered..., An alternative could be...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        1. When generating prompts for...
        2. For users who need to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Critical (blocking my workflow)
        - High (would significantly improve experience)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images here, or link to examples...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Any additional information that might help...
